apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  BACKEND_PORT: {{ .Values.config.backendPort | quote }}
  CORS_ALLOW_ORIGINS: "https://{{ .Values.ingress.host }}"
  REACT_APP_API_BASE_URL: "/api"
  OLLAMA_MODEL: {{ .Values.config.ollamaModel | quote }}