{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled .Values.ingress.tls.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.ingress.tls.secretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/certs/tls.crt" | b64enc | quote }}
  tls.key: {{ .Files.Get "files/certs/tls.key" | b64enc | quote }}
{{- end }}