apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-exporter-config
  namespace: todolist
data:
  exporter.cnf: |
    [client]
    user=exporter
    password=exporter_password
    host=mysql-service
    port=3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter-deployment
  namespace: todolist
  labels:
    app: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: db-exporter
          image: prom/mysqld-exporter:latest
          ports:
            - containerPort: 9104
          args:
            - "--config.my-cnf=/etc/db-exporter/exporter.cnf"
          volumeMounts:
            - name: db-exporter-config
              mountPath: /etc/db-exporter
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          livenessProbe:
            httpGet:
              path: /
              port: 9104
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 9104
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: db-exporter-config
          configMap:
            name: mysql-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter-service
  namespace: todolist
  labels:
    app: mysql-exporter
spec:
  selector:
    app: mysql-exporter
  ports:
    - protocol: TCP
      port: 9104
      targetPort: 9104
  type: ClusterIP

