apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-analytics-deployment
  namespace: todolist
  labels:
    app: flask-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-analytics
  template:
    metadata:
      labels:
        app: flask-analytics
    spec:
      containers:
      - name: flask-analytics
        image: erenozcan17/flask_analytics:v3.0
        ports:
        - containerPort: 5000
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus-service:9090/prometheus"
        - name: OLLAMA_URL
          value: "http://ollama-service:11434"
        - name: OLLAMA_MODEL
          value: "qwen3:latest"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
