apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-analytics-deployment
  namespace: todolist
  labels:
    app: flask-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-analytics
  template:
    metadata:
      labels:
        app: flask-analytics
    spec:
      containers:
      - name: flask-analytics
        image: erenozcan17/flask_analytics:v3.1
        ports:
        - containerPort: 5000
        env:
        - name: PROMETHEUS_URL
          value: "https://prometheus-service:9090/prometheus"
        - name: OLLAMA_URL
          value: "https://ollama-service:11434"
        - name: OLLAMA_MODEL
          valueFrom:
            configMapKeyRef:
              name: config
              key: OLLAMA_MODEL
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: flask-analytics-service
  namespace: todolist
  labels:
    app: flask-analytics
spec:
  selector:
    app: flask-analytics
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
