apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
  namespace: todolist
  labels:
    app: go-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              echo "Waiting for MySQL to be ready..."
              until nc -z mysql-service 3306; do
                echo "MySQL is not ready yet. Waiting..."
                sleep 2
              done
              echo "MySQL is ready!"
              
              # MySQL bağlantısını test et
              echo "Testing MySQL connection..."
              sleep 5
              echo "MySQL connection test completed."
      containers:
        - name: go-api
          image: erenozcan17/go_backend:v4.1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: JWT_SECRET
            - name: CORS_ALLOW_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: CORS_ALLOW_ORIGINS
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: BACKEND_PORT
