apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: todolist
data:
  prometheus.yml: |
    apiVersion: 1
    
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://todolist.kubernetes.local/prometheus
        uid: prometheus
        isDefault: true
        editable: true
