apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-exporter-config
  namespace: todolist
data:
  exporter.cnf: |
    [client]
    user=exporter
    password=exporter_password
    host=mysql-service
    port=3306

