apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-react-app-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: {{ .Values.reactApp.service.port }}
      targetPort: {{ .Values.reactApp.service.port }}
  type: {{ .Values.reactApp.service.type }}