apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-exporter-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  .my.cnf: |
    {{- printf "[client]\nuser=%s\npassword=%s\nhost=%s\nport=%s" .Values.secrets.exporterUser .Values.secrets.exporterPassword .Values.config.dbHost .Values.config.dbPort | b64enc | nindent 4 }}