apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-exporter-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysql-exporter
spec:
  selector:
    app: mysql-exporter
  ports:
    - protocol: TCP
      port: {{ .Values.dbExporter.service.port }}
      targetPort: {{ .Values.dbExporter.service.port }}
  type: {{ .Values.dbExporter.service.type }}