apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-blackbox-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: blackbox-exporter
spec:
  replicas: {{ .Values.blackboxExporter.replicaCount }}
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: "{{ .Values.blackboxExporter.image.repository }}:{{ .Values.blackboxExporter.image.tag }}"
          imagePullPolicy: {{ .Values.blackboxExporter.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.blackboxExporter.service.port }}
          args:
            - '--config.file=/etc/blackbox_exporter/config.yml'
          volumeMounts:
            - name: blackbox-config-volume
              mountPath: /etc/blackbox_exporter/
          resources:
          {{- toYaml .Values.blackboxExporter.resources | nindent 10 }}
      volumes:
        - name: blackbox-config-volume
          configMap:
            name: {{ .Release.Name }}-blackbox-config