apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-blackbox-exporter-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: blackbox-exporter
spec:
  selector:
    app: blackbox-exporter
  ports:
    - name: http
      port: {{ .Values.blackboxExporter.service.port }}
      targetPort: {{ .Values.blackboxExporter.service.port }}
  type: {{ .Values.blackboxExporter.service.type }}