{{- if and .Values.mysql.persistence.enabled .Values.mysql.persistence.createPv }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mysql-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.mysql.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.mysql.persistence.reclaimPolicy }}
  storageClassName: {{ .Values.mysql.persistence.storageClassName }}
  hostPath:
    path: {{ .Values.mysql.persistence.hostPath }}
{{- end }}