apiVersion: v1
kind: Service
metadata:
  name: mysql-service # Bu ismi sabit bırakmak, configmap'teki DB_HOST değeriyle uyumlu olmasını sağlar.
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.port }}
      protocol: TCP
  type: {{ .Values.mysql.service.type }}