apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-node-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      hostNetwork: {{ .Values.nodeExporter.hostNetwork }}
      hostPID: {{ .Values.nodeExporter.hostPID }}
      containers:
        - name: node-exporter
          image: "{{ .Values.nodeExporter.image.repository }}:{{ .Values.nodeExporter.image.tag }}"
          imagePullPolicy: {{ .Values.nodeExporter.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.nodeExporter.service.port }}
              hostPort: {{ .Values.nodeExporter.service.port }}
          args:
          {{- toYaml .Values.nodeExporter.args | nindent 10 }}
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: root
              mountPath: /host
              readOnly: true
          resources:
          {{- toYaml .Values.nodeExporter.resources | nindent 10 }}
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
      tolerations:
        {{- toYaml .Values.nodeExporter.tolerations | nindent 8 }}