apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node-exporter-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: node-exporter
spec:
  selector:
    app: node-exporter
  ports:
    - name: metrics
      port: {{ .Values.nodeExporter.service.port }}
      targetPort: {{ .Values.nodeExporter.service.port }}
  type: {{ .Values.nodeExporter.service.type }}